//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenSlicer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenSlicer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string RemoveItemCommand_Popup_Caption {
            get {
                return ResourceManager.GetString("RemoveItemCommand.Popup.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove item &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveItemCommand_Popup_Message {
            get {
                return ResourceManager.GetString("RemoveItemCommand.Popup.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action changes the target region to compensate the difference between the actual and visible window sizes..
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_CorrectTargetRegionData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.CorrectTargetRegionData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct target region.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_CorrectTargetRegionData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.CorrectTargetRegionData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action changes the target region.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_ModifyTargetRegionData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.ModifyTargetRegionData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify target region.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_ModifyTargetRegionData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.ModifyTargetRegionData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user32.MoveWindow.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32MoveWindowData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32MoveWindowData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [User32.dl] MoveWindow.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32MoveWindowData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32MoveWindowData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user32.PostMessage.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32PostMessageData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32PostMessageData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [User32.dll] PostMessage.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32PostMessageData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32PostMessageData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user32.SetWindowPos.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32SetWindowPosData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32SetWindowPosData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [User32.dll] SetWindowPos.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32SetWindowPosData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32SetWindowPosData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user32.ShowWindow.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32ShowWindowData_Description {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32ShowWindowData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [User32.dll] ShowWindow.
        /// </summary>
        internal static string ScreenSlicer_Compatibility_Actions_User32ShowWindowData_Name {
            get {
                return ResourceManager.GetString("ScreenSlicer.Compatibility.Actions.User32ShowWindowData.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsWindow_About_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.About.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string SettingsWindow_Compatibility_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.Compatibility.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string SettingsWindow_Localization_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.Localization.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snaps.
        /// </summary>
        internal static string SettingsWindow_Snaps_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.Snaps.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SettingsWindow_System_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.System.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Slicer v.{0}.
        /// </summary>
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string SettingsWindow_Updates_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.Updates.GroupHeader", resourceCulture);
            }
        }
    }
}
